### ISSUE TITLE
Development Env

### ISSUE THREAD

**Issue by oroojlooy** [dendisuhubdy/libtorch_examples#1]
Hi, 

May I ask which environment you used? and which IDE?
I am asking since I do have some problem with indexing in Linux with Eclipse and running problem in Windows with Eclipse. 

Best,
Afshin

**Comment by dendisuhubdy** [comment]
Hi @oroojlooy I'm using Max OS X 10.14 Mojave to compile the program with the latest xcode commandline tools. I used Vim (a text editor popular for programming in terminal). To compile it open Terminal in Mac OS or Linux then do.

```bash
cd $PROJECT_DIR # for example ~/dev/libtorch_examples
mkdir build
cmake ..
make -j8
./src/mnist # to see mnist training
```

Let me know if that helps.

**Comment by oroojlooy** [comment]
Thanks @dendisuhubdy for the explanation. I also was able to compile and run Libtorch examples through terminal in Linux, though I am looking for a more powerful IDE like Eclipse or CLion.

**Comment by dendisuhubdy** [comment]
Maybe CLion might be better :)
